src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;


    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="tasks")
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, mappedBy="tasks")
     * * @JoinTable(name="tag_task",
     *      joinColumns={@JoinColumn(name="tag_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="task_id", referencedColumnName="id")}
     *      )
     */
    private Collection $tags;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Generates the magic method
     *
     */
    public function __toString() {
        return $this->name;
    }

    /**
     * @return Collection|user[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(user $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(user $user): self
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addTask($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeTask($this);
        }

        return $this;
    }

}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('created_at',DateTimeType::class, [
                'input' => 'datetime',
                'with_seconds' => false,
                'html5' => true,
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'combinedPickerInput',
                    'placeholder' => date('d/M/y H:m'),
                ],
                'format' => 'dd/MM/yyyy H:mm',
                'date_format' => 'd/m/Y H:mm',
                'translation_domain' => 'Default',
                'required' => false,
            ])
            ->add('tags', CollectionType::class, [
                'entry_type' => TagType::class,
                'entry_options' => [
                    'required'  => false,
                    'attr' => array (
                        'class' => 'form-control',

                    ),
                ],
                'label' => false,
                'allow_delete' => true,
                'allow_add' => true,
                'by_reference' => false,

            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class TaskController extends AbstractController
{
    /**
     * @Route("/tasks/list", name="task_list")
     */
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    /**
     * @Route("/task/new", name="task_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('task_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/tasks/list/{id}", name="task_show", methods={"GET", "POST"})
     */
    public function show(int $id): Response
    {
        $task = $this->getDoctrine()->getRepository(Task::class)->find($id);
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    /**
     * @Route("/task/{id}/edit", name="task_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, int $id, EntityManagerInterface $entityManager): Response
    {
        $task = $this->getDoctrine()->getRepository(Task::class)->find($id);
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($task);
            $entityManager->flush();;

            return $this->redirectToRoute('task_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="task_delete", methods={"POST"})
     */
    public function delete(Request $request, Task $task): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('task_list', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/task/{id}/add", name="task_user", methods={"GET","POST"})
     */
    public function addUser(int $id): Response
    {

        $user = $this->getUser();
        $registeredTask = $this->getDoctrine()->getRepository(Task::class)->find($id);
        $registeredTask->addUser($user);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->persist($registeredTask);
        $entityManager->flush();

        return $this->redirectToRoute('user_show');

    }

    /**
     * @Route("/task/{id}/delete", name="task_user_delete", methods={"GET","POST"})
     */
    public function deleteUser(int $id): Response
    {

        $user = $this->getUser();
        $registeredTask = $this->getDoctrine()->getRepository(Task::class)->find($id);
        $registeredTask->removeUser($user);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->persist($registeredTask);
        $entityManager->flush();

        return $this->redirectToRoute('user_show');

    }
}

templates/task/_delete_form.html.twig
<form method="post" style="display:inline" action="{{ path('task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this task?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn btn-danger">
        <i class="fa fa-btn fa-user"></i> {{ button_label|default('Delete') }}
    </button>
</form>

templates/task/_form.html.twig
<div class="container">
    <div class="row">
        <div class="col-md-10 ml-md-auto">
            <div class="card bg-light mb-3 mt-5" style="width: 800px">
                <div class="card-body">
                    <div class="card-header mb-3">Create Task</div>
                    {{ form_start(form) }}
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {{ form_row(form.created_at, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {% if form.tags is not empty %}
                                {{ form_label(form.tags, "Tags")}}
                            {% endif %}
                            {{ form_label(form.tags, "")}}
                            {% for tag in form.tags %}
                                <div class="form_group">
                                    <div class="col-md-12 mb-3 bg-white" style="padding-bottom: 1rem">
                                        {{ form_row(tag.name, {'attr': {'class':'form-control', 'readonly':'true'}}) }}
                                        {{ form_row(tag.description, {'attr': {'class':'form-control','readonly':'true'}}) }}
                                        {{ form_row(tag.tasks, {'attr': {'class':'form-control'}}) }}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row" style="margin-left:5px;">
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
                                <button class="btn btn-primary">
                                    <i class="fa fa-btn fa-user"></i> {{ button_label|default('Save') }}
                                </button>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4" style="margin-top:-3px;">
                                <a class="btn btn-primary" href="{{ path('tag_task_add') }}" role="button" style="margin:8px">Create new tag</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
                                <a class="btn btn-primary" href="{{ path('task_list',) }}" role="button">Back</a>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task List{% endblock %}

{% block body %}
    <h1>Task List</h1>
<a class="btn btn-primary btn-lg" href="{{ path('task_new') }}" role="button" style="margin:8px">Create new task</a>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Created at</th>
                <th>Tag</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.name }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.createdAt ? task.createdAt|date('d-m-Y H:i') : '' }}</td>
                <td>
                    {% for tag in task.tags %}
                        <div>
                            {{ tag }}
                        </div>
                    {% else %}
                        no tags
                    {% endfor %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{{ path('task_edit', {'id': task.id}) }}" role="button">Edit</a>
                    <a class="btn btn-primary" href="{{ path('task_show', {'id': task.id}) }}" role="button">Show</a>
                    {{ include('task/_delete_form.html.twig')}}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
    <h1>Create new Task</h1>

    {{ include('task/_form.html.twig') }}

{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>
<div class="table-responsive">
    <table class="table table-sm table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Created at</th>
                <th>Tag</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ task.name }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.createdAt ? task.createdAt|date('d-m-Y H:i') : '' }}</td>
                <td>
                    {% for tag in task.tags %}
                        <div>
                            {{ tag }}
                        </div>
                    {% else %}
                        no tag
                    {% endfor %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{{ path('task_edit', {'id': task.id}) }}" role="button">Edit</a>
                    <a class="btn btn-primary" href="{{ path('task_show', {'id': task.id}) }}" role="button">Show</a>
                    <a class="btn btn-primary" href="{{ path('task_list', {'id': task.id}) }}" role="button">Back</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}